image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  REPREPRO_BASE: "/srv/repository/ubuntu"

before_script:
  - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    
deploy:
  stage: deploy
  script:
    - |
      if [[ $VERSION = *"SNAPSHOT" || $VERSION = *"RELEASE" ]]; then
        mvn $MAVEN_CLI_OPTS deploy
        
        echo "Building Debian package for $VERSION"
        mvn $MAVEN_CLI_OPTS -U -Pdariah.deb -Dmaven.test.failure.ignore package
        
        mv colreg-ui/target/*.deb target/

        echo "Building documentation"
        cd docs

        echo "-- Setting up Virtualenv"
        virtualenv venv
        pwd
        . venv/bin/activate

        echo "-- Installing requirements"
        pip install -r requirements.txt

        echo "-- Building HTML version within $(pwd)"
        make clean html

        echo "-- Creating package"
        fpm -t deb -a noarch -s dir --name colreg-doc \
                              --description='DARIAH-DE ColReg Documentation' \
                              --maintainer='DARIAH-DE <info@de.dariah.eu>' \
                              --vendor='DARIAH-DE' \
                              --url='https://colreg.de.dariah.eu' \
                              --version $VERSION \
                              -x ".git**" \
                              -x "**/.git**" \
                              -x "**/.hg**" \
                              -x "**/.svn**" \
                              -x ".buildinfo" \
                              -x "**/*.deb" \
                              --prefix /var/www/doc/colreg \
                              -C _build/html .

        mv *.deb ../target
        
        ~/push_deb_packages.sh ../target
        
      fi