#!/bin/bash
# invoke-rc.d tomcat7 start
# init mongo db
echo "testitest"
for I in * do; echo $I; done
# FIXME do we need any checks here before adding this data to the database?
mongoimport ./WEB-INF/classes/initialization_data/accessType.json
mongoimport ./WEB-INF/classes/initialization_data/accrualPeriodicity.json
mongoimport ./WEB-INF/classes/initialization_data/agentRelationType.json
mongoimport ./WEB-INF/classes/initialization_data/itemType.json
mongoimport ./WEB-INF/classes/initialization_data/licenseGroup.json
mongoimport ./WEB-INF/classes/initialization_data/accrualMethod.json
mongoimport ./WEB-INF/classes/initialization_data/accrualPolicy.json
mongoimport ./WEB-INF/classes/initialization_data/agentType.json
mongoimport ./WEB-INF/classes/initialization_data/language.json
# return success, even if service not installed
exit 0
