#!/bin/bash
# invoke-rc.d tomcat7 start
# init mongo db
mongoimport accessType.json
mongoimport accrualPeriodicity.json
mongoimport agentRelationType.json
mongoimport itemType.json
mongoimport licenseGroup.json
mongoimport accrualMethod.json
mongoimport accrualPolicy.json
mongoimport agentType.json
mongoimport language.json
# return success, even if service not installed
exit 0
